### ISSUE TITLE
[Arch] ImportError: No module named QtWebKit

### ISSUE THREAD

**Issue by wallace11** [scottwernervt/clipmanager#13]
According to the following announcement (https://www.archlinux.org/todo/phasing-out-qtwebkit/) QtWebKit support has been phased out.
Running clipmanager installed from AUR results in the following error:
```
Traceback (most recent call last):
  File "/usr/bin/clipmanager", line 10, in <module>
    from clipmanager.app import main
  File "/usr/lib/python2.7/site-packages/clipmanager/app.py", line 14, in <module>
    from clipmanager.ui.mainwindow import MainWindow
  File "/usr/lib/python2.7/site-packages/clipmanager/ui/mainwindow.py", line 33, in <module>
    from clipmanager.ui.dialogs.preview import PreviewDialog
  File "/usr/lib/python2.7/site-packages/clipmanager/ui/dialogs/preview.py", line 9, in <module>
    from PySide.QtWebKit import QWebSettings, QWebView
ImportError: No module named QtWebKit
```

**Comment by scottwernervt** [comment]
Thanks for reporting the issue. The code no longer depends on QtWebKit. The aur package [clipmanager](https://aur.archlinux.org/packages/clipmanager) has been updated to v0.5.0.
